name = "chatai-backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
AI_MODEL = "gpt-4.1-nano"
AI_PROVIDER = "openai"
SYSTEM_PROMPT = "You are a helpful assistant."

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "a43063553af247229d0ee9c362e31bd3"
preview_id = "a43063553af247229d0ee9c362e31bd3"

# Producer — chatai-backend bisa kirim ke queue ini
[[queues.producers]]
binding = "CHAT_RETRY_QUEUE"
queue = "chat-retry-queue"

# Consumer — chatai-backend proses pesan dari queue ini
[[queues.consumers]]
queue = "chat-retry-queue"
max_batch_size = 10
max_retries = 3

[[durable_objects.bindings]]
name = "THREAD_CHAT_DO"
class_name = "ThreadChatDO"

[[migrations]]
tag = "v1"
new_classes = ["ThreadChatDO"]
